apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pine
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
