apiVersion: apps/v1
kind: Deployment
metadata:
  name: pine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pine
      app.kubernetes.io/part-of: pine
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pine
        app.kubernetes.io/part-of: pine
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pine
                topologyKey: kubernetes.io/hostname
      containers:
        - name: pine
          image: docker.pkg.github.com/sjparkinson/pine/pine:latest
          envFrom:
            - secretRef:
                name: pine
                optional: false
          env:
            - name: RAILS_ENV
              value: production
            - name: RACK_ENV
              value: production
            - name: LOG_LEVEL
              value: info
            - name: MALLOC_ARENA_MAX
              value: '2'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 512Mi
          livenessProbe: &healthcheck
            httpGet:
              path: /healthz
              port: 80
              httpHeaders:
                - name: Host
                  value: pine.uncomplicated.systems
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 30
          readinessProbe:
            <<: *healthcheck
      imagePullSecrets:
        - name: github
