apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pine-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: pine.uncomplicated.systems
      http:
        paths:
          - backend:
              serviceName: pine
              servicePort: 80
