apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pod-disruption-budget.yaml
  - postgres.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/part-of: pine
