apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pine-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pine
      app.kubernetes.io/part-of: pine
